"""Created on 2026-08-09.

the hop set file of a reel

@author: wf
"""

from typing import List, Optional

from basemkit.yamlable import lod_storable

from rdd.config import HopConfig
from rdd.recording import HopContent, Recording

HEADER = """# Reel Driven Development - hop set
# https://github.com/WolfgangFahl/reel-driven-development
# method: https://wiki.bitplan.com/index.php/Reel_Driven_Development
# generated by hopdetect {version} on {date}
"""


@lod_storable
class HopSet:
    """The complete record of one hop detection run.

    The reel and the values that decided the hop set belong in the file
    that carries the hops: a hop set read a year later is only evidence
    if it says which reel it describes and what produced it. recording is
    the Recording of https://contexts.bitplan.com/index.php/Concept:Recording
    so the file reads straight back into the model and its hopCount can be
    compared with the number of hop records.
    """

    recording: Optional[Recording] = None
    config: Optional[HopConfig] = None
    hops: List[HopContent] = None

    def __post_init__(self):
        """Start with an empty hop list where none was given."""
        if self.hops is None:
            self.hops = []

    def save(self, path: str, version: str, date: str) -> None:
        """Save this hop set with the header that says where it comes from.

        Args:
            path: the file to write.
            version: the version of hopdetect that produced this hop set.
            date: the ISO date of the run.

        Returns:
            None
        """
        header = HEADER.format(version=version, date=date)
        yaml_text = self.to_yaml()
        with open(path, "w", encoding="utf-8") as hop_file:
            hop_file.write(header)
            hop_file.write("\n")
            hop_file.write(yaml_text)
