"""Created on 2026-08-09.

the reel file - the record of one reel and its hops

@author: wf
"""

import os
from typing import List, Optional

from basemkit.yamlable import lod_storable

from rdd.config import HopConfig
from rdd.recording import HopContent, Recording

HEADER = """# Reel Driven Development - reel
# https://github.com/WolfgangFahl/reel-driven-development
# method: https://wiki.bitplan.com/index.php/Reel_Driven_Development
# generated by hopdetect {version} on {date}
"""


@lod_storable
class HopSet:
    """The record of one reel: what it is, what produced its hops and the
    hops themselves.

    The reel and the values that decided the hop set belong in the file
    that carries the hops: a hop set read a year later is only evidence
    if it says which reel it describes and what produced it. recording is
    the Recording of https://contexts.bitplan.com/index.php/Concept:Recording
    so the file reads straight back into the model.

    The file is also the input of a run: what only a person knows - the
    name, the acronym, the date, the participants, the language - is
    written into a hopless file beforehand and kept when the hops are
    added, so a detection never invents the identity of a reel and never
    loses it (issue #24).

    hopCount is not stored: in this file it would be the length of the
    hop list a second time and could only ever disagree with it. The
    equality it controls is the one on the wiki page, where the hops are
    subobjects.
    """

    FILE_NAME = "reel.yaml"

    recording: Optional[Recording] = None
    config: Optional[HopConfig] = None
    hops: List[HopContent] = None

    def __post_init__(self):
        """Start with an empty hop list where none was given."""
        if self.hops is None:
            self.hops = []

    @property
    def hopCount(self) -> int:
        """The number of hops of this reel."""
        hop_count = len(self.hops)
        return hop_count

    @classmethod
    def path_of(cls, out_dir: str) -> str:
        """Get the path of the reel file in the given directory.

        Args:
            out_dir: the recording directory.

        Returns:
            the path of the reel file.
        """
        reel_path = os.path.join(out_dir, cls.FILE_NAME)
        return reel_path

    @classmethod
    def of_dir(cls, out_dir: str) -> Optional["HopSet"]:
        """Get the reel file of the given directory.

        Args:
            out_dir: the recording directory.

        Returns:
            the hop set, None where the directory carries no reel file.
        """
        reel_path = cls.path_of(out_dir)
        hop_set = None
        if os.path.isfile(reel_path):
            hop_set = cls.load_from_yaml_file(reel_path)
        return hop_set

    def save(self, path: str, version: str, date: str) -> None:
        """Save this reel with the header that says where it comes from.

        Args:
            path: the file to write.
            version: the version of hopdetect that produced this hop set.
            date: the ISO date of the run.

        Returns:
            None
        """
        header = HEADER.format(version=version, date=date)
        yaml_text = self.to_yaml()
        with open(path, "w", encoding="utf-8") as reel_file:
            reel_file.write(header)
            reel_file.write("\n")
            reel_file.write(yaml_text)
